<?php

//Get the connection from the included files 

require '../../includeFiles/Connection.php';

$getParam = $_POST['reportType'];

//request for the pdf file to print it to the screen

require '../fpdf/fpdf.php';



//A4 width : 219mm
//default margin : 10mm each side
//writable horizontal : 219-(10*2)=189mm

//create pdf object
$pdf = new FPDF('P','mm','A3');
//add new page
$pdf->AddPage();
//set font to arial, bold, 14pt
$pdf->SetFont('Arial','B',14);

$title = 'SUNBI CLINIC';

 if($getParam == 'allPatients'){
 	$pdf->Cell(130 ,5,'',0,0);
        $pdf->Cell(59 ,5,'All Patients List Report',0,1);//end of line

        //set font to arial, regular, 12pt
        // $pdf->SetFont('Arial',''.$title,12);

        $pdf->Cell(130 ,5,'Generated By: Mercy',0,0);
        $pdf->Cell(59 ,5,'',0,1);//end of line

        $currentDate = date('d/m/Y');
        $pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
        $pdf->Cell(20 ,5,'Date',0,0);
        $pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line



        //make a dummy empty cell as a vertical spacer
        $pdf->Cell(189 ,10,'',0,1);//end of line


        //invoice contents
        $pdf->SetFont('Arial','B',12);

        $pdf->Cell(60 ,5,'Full Name',1,0);
        $pdf->Cell(50 ,5,'Date of Birth',1,0);
        $pdf->Cell(60 ,5,'NRCNUMBER',1,0);//end of line
        $pdf->Cell(60,5,'Date Account Added',1,0);
        $pdf->Cell(34,5,'Unique Number',1,1);

        $getAllPatients = "SELECT * FROM patients ";
        $getPatientsQuery = mysqli_query($con, $getAllPatients);
        $getPatientsNum = mysqli_num_rows($getPatientsQuery);

        if ($getPatientsNum > 0) {
            # code...

            while ($getPatients = mysqli_fetch_assoc($getPatientsQuery)) {
                # code...
                $account_number = $getPatients['fullname'];
                $account_holder = $getPatients['dob'];
                $balance = $getPatients['nrc'];

                $pdf->Cell(60,5,''.$account_number.'',1,0);
                $pdf->Cell(50,5,''.$account_holder.'',1,0);
                $pdf->Cell(60,5,' '.$balance.'',1,0,'L');
                $pdf->Cell(60,5,''.$getPatients['dateRegistered'],1,0,'L');
                $pdf->Cell(34,5,''.ucfirst($getPatients['uniqueID']),1,1,'L');//end of line
            }
        }


        $pdf->SetFont('Arial','',12);

        //Numbers are right-aligned so we give 'R' after new line parameter
        $pdf->Output();

 } else if ($getParam == 'allStaff') {
 	# code...
 		$pdf->Cell(130 ,5,'',0,0);
        $pdf->Cell(59 ,5,'All Staff List Report',0,1);//end of line

        //set font to arial, regular, 12pt
        // $pdf->SetFont('Arial',''.$title,12);

        $pdf->Cell(130 ,5,'Generated By: Mercy',0,0);
        $pdf->Cell(59 ,5,'',0,1);//end of line

        $currentDate = date('d/m/Y');
        $pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
        $pdf->Cell(20 ,5,'Date',0,0);
        $pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line



        //make a dummy empty cell as a vertical spacer
        $pdf->Cell(189 ,10,'',0,1);//end of line


        //invoice contents
        $pdf->SetFont('Arial','B',12);

        $pdf->Cell(50 ,5,'Full Name',1,0);
        $pdf->Cell(40 ,5,'Date of Birth',1,0);
        $pdf->Cell(40 ,5,'NRCNUMBER',1,0);//end of line
        $pdf->Cell(60,5,'Email Address',1,0);
            $pdf->Cell(50,5,'Date Account Added',1,0);
        $pdf->Cell(34,5,'Staff Number',1,1);

        $getAllStaff = "SELECT * FROM staff ";
        $getStaffQuery = mysqli_query($con, $getAllStaff);
        $getStaffNum = mysqli_num_rows($getStaffQuery);

        if ($getStaffNum > 0) {
            # code...
				
            while ($getStaff = mysqli_fetch_assoc($getStaffQuery)) {
                # code...
                $staffFullName = $getStaff['staffName'];
                $staffDOB = $getStaff['staffDOB'];
                $nrc = $getStaff['nrc'];

                $pdf->Cell(50,5,''.$staffFullName.'',1,0);
                $pdf->Cell(40,5,''.$staffDOB.'',1,0);
                $pdf->Cell(40,5,' '.$nrc.'',1,0,'L');
                $pdf->Cell(60,5,''.$getStaff['staffEmail'].'',1,0,'L');
                $pdf->Cell(50,5,''.$getStaff['dateRegistered'],1,0,'L');
                $pdf->Cell(34,5,''.ucfirst($getStaff['staffNumber']),1,1,'L');//end of line
            }
        }


        $pdf->SetFont('Arial','',12);

        //Numbers are right-aligned so we give 'R' after new line parameter
        $pdf->Output();

 } else if($getParam == 'diseaseHistory'){
 	$pdf->Cell(130 ,5,'',0,0);
				$pdf->Cell(59 ,5,'All Disease History Records',0,1);//end of line

				//set font to arial, regular, 12pt
				// $pdf->SetFont('Arial',''.$title,12);

				$pdf->Cell(130 ,5,'Generated By: Mercy',0,0);
				$pdf->Cell(59 ,5,'',0,1);//end of line

				$currentDate = date('d/m/Y');
				$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
				$pdf->Cell(20 ,5,'Date',0,0);
				$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line

				

				//make a dummy empty cell as a vertical spacer
				$pdf->Cell(189 ,10,'',0,1);//end of line

				
				//invoice contents
				$pdf->SetFont('Arial','B',12);

				$pdf->Cell(60 ,5,'Patient Name',1,0);
				$pdf->Cell(35,5,'Patient Number',1,0);
				$pdf->Cell(50 ,5,'Staff Name',1,0);
				$pdf->Cell(50 ,5,'Disease Name',1,0);//end of line
				$pdf->Cell(40,5,'CP Time Started ',1,0);
				$pdf->Cell(40,5,'CP Time Ended',1,1);
			
				$pdf->Cell(275 ,5,'',1,1);
				// $pdf->Cell(35,5,'',1,0);
				// $pdf->Cell(50 ,5,'',1,0);
				// $pdf->Cell(50 ,5,'',1,0);//end of line
				// $pdf->Cell(40,5,'',1,0);
				// $pdf->Cell(40,5,'',1,1);

				$getAllStaff = "SELECT patients.fullname, patients.uniqueID, activeLog.cpTimeStarted, activeLog.cpTimeEnded, diseaseRecord.diseaseName, staff.staffName FROM staff, patients, activeLog, diseaseRecord WHERE activeLog.id = diseaseRecord.aid AND patients.uniqueID = diseaseRecord.pID AND staff.staffNumber = activeLog.coID ";
				$getStaffQuery = mysqli_query($con, $getAllStaff);
				$getStaffNum = mysqli_num_rows($getStaffQuery);

				if ($getStaffNum > 0) {
					# code...
				
					while ($getStaff = mysqli_fetch_assoc($getStaffQuery)) {
						# code...
						$staffFullName = $getStaff['staffName'];
						$patientName = $getStaff['fullname'];
						$diseaseName = $getStaff['diseaseName'];

						$pdf->Cell(60,5,''.$patientName.'',1,0);
						$pdf->Cell(35,5,''.$getStaff['uniqueID'],1,0,'L');
						$pdf->Cell(50,5,''.$staffFullName.'',1,0);
						$pdf->Cell(50,5,' '.$diseaseName.'',1,0,'L');
						$pdf->Cell(40,5,''.$getStaff['cpTimeStarted'],1,0,'L');
						$pdf->Cell(40,5,''.$getStaff['cpTimeEnded'],1,1,'L');//end of line
					}
				} else {
				$pdf->Cell(270,5,'No data avaliable right now',1,1,L);
				}


				$pdf->SetFont('Arial','',12);

				//Numbers are right-aligned so we give 'R' after new line parameter
				$pdf->Output();
 } else if ($getParam == 'singlePatient'){
 	$getID = $_POST['pUniqueID'];

 	$Explo = explode(" ", $getID);

 	$namePassed = "";
 			for ($i=0; $i < count($Explo) ; $i++) { 
 				# code...
 				if ($Explo[$i] == 0) {
 					# code...
 					continue;
 				}

 				$namePassed .= $Explo[$i];
 			}

			$pdf->Cell(19 ,3,'PERSONAL REPORT FOR '.$namePassed,0,0);//end of line

 	 		$pdf->Cell(130 ,5,'',0,1);
			//set font to arial, regular, 12pt
			// $pdf->SetFont('Arial',''.$title,12);

			$pdf->Cell(130 ,5,'Generated By: Mercy',0,0);
			$pdf->Cell(59 ,5,'',0,1);//end of line



			$currentDate = date('d/m/Y');
			$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
			$pdf->Cell(20 ,5,'Date',0,0);
			$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line

			//Query for the patient table then pass them through the variables 

			$selectPatientDetails = "SELECT * FROM PATIENTS WHERE uniqueID = '".$Explo[0]."'" ;
			$querySelect = mysqli_query($con, $selectPatientDetails);
			while ($rows = mysqli_fetch_assoc($querySelect)) {
				# code...
				$pdf->Cell(130,5, 'Physical Address: '.$rows['physicalAddress'],0,0);
				$pdf->Cell(130,5, 'Next to Kin: '.$rows['nextToKin'],0,1);
				$pdf->Cell(130,5, 'Phone Number: '.$rows['phoneNumber'],0,0);
				$pdf->Cell(130,5, 'Date of Birth: '.$rows['dob'],0,1);
				$pdf->Cell(130,5, 'Nrc Number: '.$rows['nrc'],0,0);
				$pdf->Cell(130,5, 'Dated Registered '.$rows['dateRegistered'],0,1);
			}
			

			

			//make a dummy empty cell as a vertical spacer
			$pdf->Cell(189 ,10,'',0,1);//end of line

			
			//invoice contents
			$pdf->SetFont('Arial','B',12);

			$pdf->Cell(60 ,5,'Patient Name',1,0);
			$pdf->Cell(35,5,'Patient Number',1,0);
			$pdf->Cell(50 ,5,'Staff Name',1,0);
			$pdf->Cell(50 ,5,'Disease Name',1,0);//end of line
			$pdf->Cell(40,5,'CP Time Started ',1,0);
			$pdf->Cell(40,5,'CP Time Ended',1,1);
		
			$pdf->Cell(275 ,5,'',1,1);
		

			$getAllStaff = "SELECT patients.fullname, patients.uniqueID, activeLog.cpTimeStarted, activeLog.cpTimeEnded, diseaseRecord.diseaseName, staff.staffName FROM staff, patients, activeLog, diseaseRecord WHERE activeLog.id = diseaseRecord.aid AND patients.uniqueID = diseaseRecord.pID AND staff.staffNumber = activeLog.coID ";
			$getStaffQuery = mysqli_query($con, $getAllStaff);
			$getStaffNum = mysqli_num_rows($getStaffQuery);

			if ($getStaffNum > 0) {
				# code...
			
				while ($getStaff = mysqli_fetch_assoc($getStaffQuery)) {
					# code...
					$staffFullName = $getStaff['staffName'];
					$patientName = $getStaff['fullname'];
					$diseaseName = $getStaff['diseaseName'];

					$pdf->Cell(60,5,''.$patientName.'',1,0);
					$pdf->Cell(35,5,''.$getStaff['uniqueID'],1,0,'L');
					$pdf->Cell(50,5,''.$staffFullName.'',1,0);
					$pdf->Cell(50,5,' '.$diseaseName.'',1,0,'L');
					$pdf->Cell(40,5,''.$getStaff['cpTimeStarted'],1,0,'L');
					$pdf->Cell(40,5,''.$getStaff['cpTimeEnded'],1,1,'L');//end of line
				}
			} else {
				$pdf->Cell(270,5,'No data avaliable right now',1,1,L);
			}


			$pdf->SetFont('Arial','',12);

			//Numbers are right-aligned so we give 'R' after new line parameter
			$pdf->Output();


 } else if ($getParam == "ageGroup") {
 	# code...

 	//Get the total count of all patients from the selected group.
 	$getAgeLowest = $_POST['startAge'];
 	$getAgeHighest = $_POST['endAge'];

 	$sqlCount = "SELECT COUNT(*) as total FROM patients WHERE age BETWEEN '$getAgeLowest' AND '$getAgeHighest'";
 	$totalPeopleInTheGroup = null;
 	$queryCount = mysqli_query($con, $sqlCount);

 	while ($rowsCount = mysqli_fetch_assoc($queryCount)) {
 		# code...
 		$totalPeopleInTheGroup = $rowsCount['total'];
 	}

			$pdf->Cell(19 ,3,'AGE REPORT FOR PATIENTS BETWEEN '.$getAgeLowest.' AND '.$getAgeHighest,0,0);//end of line

 	 		$pdf->Cell(130 ,5,'',0,1);
			//set font to arial, regular, 12pt
			// $pdf->SetFont('Arial',''.$title,12);

			$pdf->Cell(130 ,5,'Generated By: Mercy',0,0);
			$pdf->Cell(59 ,5,'',0,1);//end of line



			$currentDate = date('d/m/Y');
			$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
			$pdf->Cell(20 ,5,'Date',0,0);
			$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line

			$pdf->Cell(70,5,'Total patients with query info:[ '.$totalPeopleInTheGroup.' ]',0,1);


			//make a dummy empty cell as a vertical spacer
			$pdf->Cell(189 ,10,'',0,1);//end of line

			
			//invoice contents
			$pdf->SetFont('Arial','B',12);

			$pdf->Cell(60 ,5,'Patient Name',1,0);
			$pdf->Cell(35,5,'Patient Number',1,0);
			$pdf->Cell(30 ,5,'Age',1,0);
			$pdf->Cell(25 ,5,'Gender',1,0);
			$pdf->Cell(50 ,5,'Patient Next to kin',1,0);//end of line
			$pdf->Cell(40,5,'Physical Address',1,0);
			$pdf->Cell(40,5,'Date Added',1,1);
		
			$pdf->Cell(275 ,5,'',1,1);
		

			$getAllPatientsAgeGroup = "SELECT * FROM PATIENTS WHERE age BETWEEN '$getAgeLowest' AND '$getAgeHighest' ";
			$getAllPatientsAgeGroupQuery = mysqli_query($con, $getAllPatientsAgeGroup);
			$getStaffNum = mysqli_num_rows($getAllPatientsAgeGroupQuery);

			if ($getStaffNum > 0) {
				# code...
			
				while ($getAGPatient = mysqli_fetch_assoc($getAllPatientsAgeGroupQuery)) {
					# code...
				

					$pdf->Cell(60,5,''.$getAGPatient['fullname'].'',1,0);
					$pdf->Cell(35,5,''.$getAGPatient['uniqueID'],1,0,'L');
					$pdf->Cell(30,5,''.$getAGPatient['age'].'',1,0);
					$pdf->Cell(25,5,''.$getAGPatient['gender'].'',1,0);
					$pdf->Cell(50,5,' '.$getAGPatient['nextToKin'].'',1,0,'L');
					$pdf->Cell(40,5,''.$getAGPatient['physicalAddress'],1,0,'L');
					$pdf->Cell(40,5,''.$getAGPatient['dateRegistered'],1,1,'L');//end of line
				}
			} else {
				$pdf->Cell(270,5,'No data avaliable right now',1,1,L);
			}


			$pdf->SetFont('Arial','',12);

			//Numbers are right-aligned so we give 'R' after new line parameter
			$pdf->Output();

 }else if ($getParam == "genderReport") {
 	# code...

 	//Get the total count of all patients from the selected group.
 	$selectedGender = $_POST['selectedGender'];
 	$getAgeHighest = $_POST['endAge'];

 	$sqlCount = "SELECT COUNT(*) as total FROM patients WHERE gender = '$selectedGender'";
 	$totalPeopleInTheGroup = null;
 	$queryCount = mysqli_query($con, $sqlCount);
     

 	while ($rowsCount = mysqli_fetch_assoc($queryCount)) {
 		# code...
 		$totalPeopleInTheGroup = $rowsCount['total'];
 	}

			$pdf->Cell(19 ,3,'GENDER REPORT FOR ALL '.$selectedGender.' PATIENTS ',0,0);//end of line

 	 		$pdf->Cell(130 ,5,'',0,1);
			//set font to arial, regular, 12pt
			// $pdf->SetFont('Arial',''.$title,12);

			$pdf->Cell(130 ,5,'Generated By: Mercy',0,0);
			$pdf->Cell(59 ,5,'',0,1);//end of line



			$currentDate = date('d/m/Y');
			$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
			$pdf->Cell(20 ,5,'Date',0,0);
			$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line

			$pdf->Cell(70,5,'Total patients with query info:[ '.$totalPeopleInTheGroup.' ]',0,1);


			//make a dummy empty cell as a vertical spacer
			$pdf->Cell(189 ,10,'',0,1);//end of line

			
			//invoice contents
			$pdf->SetFont('Arial','B',12);

			$pdf->Cell(60 ,5,'Patient Name',1,0);
			$pdf->Cell(35,5,'Patient Number',1,0);
			$pdf->Cell(30 ,5,'Age',1,0);
			$pdf->Cell(25 ,5,'Gender',1,0);
			$pdf->Cell(50 ,5,'Patient Next to kin',1,0);//end of line
			$pdf->Cell(40,5,'Physical Address',1,0);
			$pdf->Cell(40,5,'Date Added',1,1);
		
			$pdf->Cell(275 ,5,'',1,1);
		

			$getAllPatientsAgeGroup = "SELECT * FROM PATIENTS WHERE gender = '$selectedGender'";
			$getAllPatientsAgeGroupQuery = mysqli_query($con, $getAllPatientsAgeGroup);
			$getStaffNum = mysqli_num_rows($getAllPatientsAgeGroupQuery);

			if ($getStaffNum > 0) {
				# code...
			
				while ($getAGPatient = mysqli_fetch_assoc($getAllPatientsAgeGroupQuery)) {
					# code...
				

					$pdf->Cell(60,5,''.$getAGPatient['fullname'].'',1,0);
					$pdf->Cell(35,5,''.$getAGPatient['uniqueID'],1,0,'L');
					$pdf->Cell(30,5,''.$getAGPatient['age'].'',1,0);
					$pdf->Cell(25,5,''.$getAGPatient['gender'].'',1,0);
					$pdf->Cell(50,5,' '.$getAGPatient['nextToKin'].'',1,0,'L');
					$pdf->Cell(40,5,''.$getAGPatient['physicalAddress'],1,0,'L');
					$pdf->Cell(40,5,''.$getAGPatient['dateRegistered'],1,1,'L');//end of line
				}
			} else {
				$pdf->Cell(270,5,'No data avaliable right now',1,1,L);
			}


			$pdf->SetFont('Arial','',12);

			//Numbers are right-aligned so we give 'R' after new line parameter
			$pdf->Output();

 } else if($getParam == ""){
     
 }

?>